export const ServerEvents = {
    RESPONSE: "ServerEvents.RESPONSE",
    SEND_RESPONSE_TO_SERVER_CONNECTOR: "ServerEvents.SEND_RESPONSE_TO_SERVER_CONNECTOR",
    SEND_INIT_REQUEST_TO_SERVER_CONNECTOR: "ServerEvents.SEND_INIT_REQUEST_TO_SERVER_CONNECTOR",
    SEND_PLAY_REQUEST_TO_SERVER_CONNECTOR: "ServerEvents.SEND_PLAY_REQUEST_TO_SERVER_CONNECTOR",
};